// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQbi5rdHsTFXxp1FsY443zgbnTbG5eT_s',
    appId: '1:866372625015:web:aef3308978c144f9dd9c72',
    messagingSenderId: '866372625015',
    projectId: 'ecosort-app-test',
    authDomain: 'ecosort-app-test.firebaseapp.com',
    storageBucket: 'ecosort-app-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSA5o1t1f5HdK0rwM1BnRjNmZxGBG28z8',
    appId: '1:866372625015:android:6135a2856a2821a3dd9c72',
    messagingSenderId: '866372625015',
    projectId: 'ecosort-app-test',
    storageBucket: 'ecosort-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM43kZDGcdXlc2tfS7xkvoIIIQZdujGf0',
    appId: '1:866372625015:ios:c7f63b7c73f3a561dd9c72',
    messagingSenderId: '866372625015',
    projectId: 'ecosort-app-test',
    storageBucket: 'ecosort-app-test.appspot.com',
    iosBundleId: 'com.example.ecosortAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM43kZDGcdXlc2tfS7xkvoIIIQZdujGf0',
    appId: '1:866372625015:ios:c7f63b7c73f3a561dd9c72',
    messagingSenderId: '866372625015',
    projectId: 'ecosort-app-test',
    storageBucket: 'ecosort-app-test.appspot.com',
    iosBundleId: 'com.example.ecosortAppTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQbi5rdHsTFXxp1FsY443zgbnTbG5eT_s',
    appId: '1:866372625015:web:1484923cb472dd99dd9c72',
    messagingSenderId: '866372625015',
    projectId: 'ecosort-app-test',
    authDomain: 'ecosort-app-test.firebaseapp.com',
    storageBucket: 'ecosort-app-test.appspot.com',
  );
}
