// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3I4ygp-RY5KXqkXGTvBqRfDI2CfZ1qM',
    appId: '1:398639572142:web:2cd23f24f2e0547763b93f',
    messagingSenderId: '398639572142',
    projectId: 'waste-ai',
    authDomain: 'waste-ai.firebaseapp.com',
    storageBucket: 'waste-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnC7QJ5H75ZEbjA8yZxQNbsH5SOXX1K4',
    appId: '1:398639572142:android:c6659f6ee4043bbd63b93f',
    messagingSenderId: '398639572142',
    projectId: 'waste-ai',
    storageBucket: 'waste-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_09zqvMARgkFBwgcEJWiG-eJKc8qdo9c',
    appId: '1:398639572142:ios:a2fc96cdff4b50cd63b93f',
    messagingSenderId: '398639572142',
    projectId: 'waste-ai',
    storageBucket: 'waste-ai.appspot.com',
    iosBundleId: 'com.example.ecosortAppTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_09zqvMARgkFBwgcEJWiG-eJKc8qdo9c',
    appId: '1:398639572142:ios:22ab4cf1449771cc63b93f',
    messagingSenderId: '398639572142',
    projectId: 'waste-ai',
    storageBucket: 'waste-ai.appspot.com',
    iosBundleId: 'com.example.ecosortAppTest.RunnerTests',
  );
}
